### ISSUE TITLE
[Vista] Selection on Desktop is buggy

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#13]
The selection colour on an icon on the desktop using the Vista GTK theme is completely black without hover and the label isn't even highlighted at all excluding the white text...

**Comment by Elbullazul** [comment]
yeah, however, I don't know what causes this. I'll investigate and be back

**Comment by Elbullazul** [comment]
@feren since we rebased Vista on MTAC this should not happen anymore
