### ISSUE TITLE
[CRITICAL BUG] Every theme has broken menus in Cinnamon 3.2

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#15]
EVERY theme that you have a Cinnamon theme for has had their menus broken by Cinnamon 3.2 which means you just get the Cinnamon theme's menus instead...

**Comment by dominichayesferen** [comment]
For some help with fixing it: https://github.com/linuxmint/Cinnamon/issues/5921

**Comment by Elbullazul** [comment]
Wish I could work on this. I have a start of tendinitis,  so I have to take a forced break.  BTW can you point me to a cinnamon 3.2 ready os?

**Comment by cinnamoner** [comment]
@Elbullazul Have you got RSI (repetitive strain injury)? Comes from abusing the keyboard. Too early for that. Please rest your hands before it gets really chronical.

**Comment by dominichayesferen** [comment]
@Elbullazul Use Linux Mint 18.1 and then, go into /etc/apt/sources.list.d/official-package-repositories and change 'sarah' to 'serena', do a APT update, then upgrade everything, or just use Arch

**Comment by cinnamoner** [comment]
@feren Or Betsy2?

**Comment by dominichayesferen** [comment]
I don't think it's on LMDE just yet...

**Comment by cinnamoner** [comment]
@feren By the way, just how much longer do you think we can follow Cinnamon aka a moving target?

**Comment by dominichayesferen** [comment]
A long while...

**Comment by cinnamoner** [comment]
@feren Good answer.

**Comment by dominichayesferen** [comment]
Looks like there's a Pull Request to theme menus seperately like pre-3.2:
https://github.com/linuxmint/Cinnamon/issues/5934

**Comment by dominichayesferen** [comment]
@Elbullazul Temporary Fix:
Copy all of the 'popup-menu {' tag thing up to its '}' and then paste it above, but with the tag changed from 'popup-menu' to just 'menu'.

**Comment by dominichayesferen** [comment]
@Elbullazul This regression may've possibly been reversed by Cinnamon 3.2.2, wait on an Arch VM for it to arrive and then check it, I'm currently not on 3.2...

**Comment by dominichayesferen** [comment]
@Elbullazul Here's how to fix it for 3.2:
https://github.com/linuxmint/Cinnamon/issues/6056#issuecomment-264940228

**Comment by Elbullazul** [comment]
fixed, as said on #18
