### ISSUE TITLE
Luna Metallic and Olive

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#16]
I was wondering, since there hasn't been a Windows XP Silver nor Windows XP Olive theme on Cinnamon for a while that is complete, would you mind doing a Silver and Olive Green variant based off of CinnXP but with the headerbars on your XP themes? BTW, I don't care as much for Olive, but mainly Silver, Silver was my favourite theme in Windows XP for a long time...

**Comment by dominichayesferen** [comment]
@Elbullazul

**Comment by Elbullazul** [comment]
shure, I'll do that, but when I get back from my medical break :)

**Comment by dominichayesferen** [comment]
Feedback & Suggestions for a more XP-like look:
**Silver:**

- Swap the hover and pressed states of the window list, they're the opposite states in XP
- Get rid of the hover/focused effect on the right-side of the panel, it wasn't there in XP
- Change the buttons, like Olive Green, Silver has a different look for its buttons that's more metallic
- Make the focused window text white in Window List, again, that's how it worked on XP
- Get rid of the black border in GTK Menus
- Make the hover text for Start white
- Change the scrollbars, they look different (more metallic like the buttons) on Silver
- Possibly add a hover image for the menu? (It's slightly brighter than unfocused)
- Get rid of the odd black line in StarkMenu > All Programs
- There's a weird bug with odd spacing below the searchbar in Stark, I know there wasn't even a search bar in XP, but nonetheless, it was still filled up by Favourites/Recent Programs
- Make the headerbar button states more like the metacity
- Change the buttons on headerbars too to match the other buttons? (Looks better if you get the metallic buttons)
- Get rid of the white shadow below text on the Cinnamon theme, it wasn't there in XP
- Use CinnXP's Metacity as a base maybe to fix the spacing up to XPs equivalent
- Change the breadcrumbs to match the XP Silver button gradient

**Olive:**

- Same Window List bug where the states are the opposite to XP's ones in this theme
- Get rid of the black shadow on the focused Window List item
- Get rid of the hover/focused effect and stop it changing the colour of the text, they weren't there in XP
- Make the headerbar focused state look more like Metacity's (Darken the shade of green used)
- Wrong shade of green in Cinnamon hover (darker shade of green is used in XP)
- Wrong shade in GTK too and wrong selected text colour
- Menus used that same colour when focused in XP
- Same shade of green in other hover states for GTK, other than buttons and the like
- Ugly menu borders (the black ones)
- Change the scrollbars, they were different to Luna (with a green shade) in XP
- Spacing in Metacity (same as Silver)
- In XP, there is hover and pressed states for the Start Button
- Make the headerbar actual-buttons match the ones in non-headerbar GTK

**Luna:**

- No shadow on Window List and other applets' text (other than Start) in XP
- Text should be white on blue for menu item hovering
- You got the StarkMenu colours the wrong side around, flip the light-blue and white over and you'll fix that
- Main Menu should have white on blue for the selected state

That's all I've noticed

**Comment by Elbullazul** [comment]
so, let's see...

**Silver:**

- [x]  Swap the hover and pressed states of the window list, they're the opposite states in XP
- [x]  Get rid of the hover/focused effect on the right-side of the panel, it wasn't there in XP
- [x]  Change the buttons, like Olive Green, Silver has a different look for its buttons that's more metallic
- [x]  Make the focused window text white in Window List, again, that's how it worked on XP
- [ ]  ~~Get rid of the black border in GTK Menus (nevermind)~~
- [x]  Make the hover text for Start white
- [x]  Change the scrollbars, they look different (more metallic like the buttons) on Silver
- [x]  Possibly add a hover image for the menu? (It's slightly brighter than unfocused)
- [x]  Get rid of the odd black line in StarkMenu > All Programs
- [x]  There's a weird bug with odd spacing below the searchbar in Stark, I know there wasn't even a search bar in XP, but nonetheless, it was still filled up by Favourites/Recent Programs
- [x]  Make the headerbar button states more like the metacity
- [x]  Change the buttons on headerbars too to match the other buttons? (Looks better if you get the metallic buttons)
- [x]  Get rid of the white shadow below text on the Cinnamon theme, it wasn't there in XP
- [x]  Use CinnXP's Metacity as a base maybe to fix the spacing up to XPs equivalent
- [x]  Change the breadcrumbs to match the XP Silver button gradient

**Olive:**
- [x]  Same Window List bug where the states are the opposite to XP's ones in this theme
- [x]  Get rid of the black shadow on the focused Window List item
- [x]  Get rid of the hover/focused effect and stop it changing the colour of the text, they weren't there in XP
- [x]  Make the headerbar focused state look more like Metacity's (Darken the shade of green used)
- [x]  Wrong shade of green in Cinnamon hover (darker shade of green is used in XP)
- [x]  Wrong shade in GTK too and wrong selected text colour
- [x]  Menus used that same colour when focused in XP
- [x]  Same shade of green in other hover states for GTK, other than buttons and the like
- [ ]  ~~Ugly menu borders (the black ones)~~
- [ ]  Change the scrollbars, they were different to Luna (with a green shade) in XP
- [x]  Spacing in Metacity (same as Silver)
- [x]  In XP, there is hover and pressed states for the Start Button
- [x]  Make the headerbar actual-buttons match the ones in non-headerbar GTK

**Luna:**
- [x]  No shadow on Window List and other applets' text (other than Start) in XP
- [x]  Text should be white on blue for menu item hovering
- [x]  You got the StarkMenu colours the wrong side around, flip the light-blue and white over and you'll fix that
- [x]  Main Menu should have white on blue for the selected state

**Comment by Elbullazul** [comment]
BTW @feren here it shows menus with dark borders:
![winxp-metal](http://www.tcu.gov.on.ca/eng/accessibility/ont06_017867.jpg)

**Comment by dominichayesferen** [comment]
Oh, oops, forgot about them

**Comment by Elbullazul** [comment]
so, I guess that's it, except for the scrollbars in olive, which I can't seem to find. maybe you can provide those assets @feren ?

**Comment by dominichayesferen** [comment]
@Elbullazul Do you have a Windows XP ISO kicking anywhere? I don't over here... Also, Longhorn TWIWMTB got rid of the XP themes in favour of a working Aero Triggering theme

**Comment by Elbullazul** [comment]
@feren and all users of XP themes:

We are now **abandoning** all XP related themes, minus Longhorn themes & Whistler,
we are migrating our 'XP-related' efforts to the CinnXP project over @ [CinnXP themes](https://github.com/petrucci4prez/CinnXP)

Reasons of deprecation include work overflow & complexity of maintenance of multiple 'classic' CSS themes; whilst with SASS devs can updates all themes at once

we're soon moving them to a new repo; should anyone wish to continue their development & maintenance we're open to yeld the codebase & possibly other useful documentation.

Cheers,

The B00merang Project Team

**Comment by Elbullazul** [comment]
more details about the reasons here:

https://gitter.im/B00merang-Project/topics/topic/5880299f11e7a7f61db5086d/deprecation-of-xp-themes

@feren I can provide extended support for the 2017 feren OS release, but not much more
