### ISSUE TITLE
Update Windows 10 Light Theme for Cinnamon 3.2

### ISSUE THREAD

**Issue by jaszhix** [Elbullazul/Redmond-Themes#17]
Hi, I really like the W10 Light theme, and was wondering if you have plans to update it, or put it on Github. I would be willing to submit a pull request with some quick fixes for Cinnamon 3.2.

Thanks.

**Comment by Elbullazul** [comment]
@jaszhix thanks for your interest; the win10 theme is already uploaded, check it here: https://github.com/B00merang-Project/Windows-10

shure, I've had lots of complains about the theme not working in 3.2, son any help is welcome. I'll just ask you to explain what your fixes are, I want to learn the fixes to later apply them to all of my current themes.
