### ISSUE TITLE
Menu issues in LM 18.1 [All Windows Themes]

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#21]
Just got the latest version of all your themes to discover to my dismay that the menus still don't work properly in 3.2...
Here's a screenshot:
![screenshot from 2017-01-14 16-05-59](https://cloud.githubusercontent.com/assets/11057934/21956195/629426d4-da73-11e6-9569-aeadf080ee2a.png)

Also, in XP Themes, it doesn't show the correct menu background on CinnVIIStarkMenu

**Comment by dominichayesferen** [comment]
@Elbullazul This is the only real thing stopping me from developing 2017.0, can you please fix it?? >_<

**Comment by Elbullazul** [comment]
@feren what does the XP theme give? On my VM they run perfect. maybe get latest cinnvii menu?

**Comment by dominichayesferen** [comment]
@Elbullazul On the XP theme, it works 100% apart from the menu's BG which is of the blocky menus

**Comment by dominichayesferen** [comment]
@Elbullazul 
![screenshot from 2017-01-15 10-07-53](https://cloud.githubusercontent.com/assets/11057934/21961756/834ae7f4-db0a-11e6-8e66-3011eeefe9f8.png)

**Comment by dominichayesferen** [comment]
@Elbullazul Don't worry about the panel, that's just a Cinnamon issue that's been around for a long time

**Comment by dominichayesferen** [comment]
@Elbullazul The fix for the menus is in this theme:
[CinnXP.tar.gz](https://github.com/Elbullazul/Redmond-Themes/files/706517/CinnXP.tar.gz)
(I built it for you to make your life easier)

**Comment by cinnamoner** [comment]
@feren So, are you rebasing Feren OS on 18.1?

**Comment by dominichayesferen** [comment]
@cinnamoner Nah, just upgrading the base the old fashioned way through the command line...
https://github.com/feren/ferenOSProjectUpdates/issues/3

**Comment by dominichayesferen** [comment]
Tried the latest version of it in Linux Mint 18.1-based 2017.0 Pre-Alpha, still getting that issue on 7 themes, and possibly Vista too...

**Comment by Elbullazul** [comment]
@feren as explained @ #16 we're moving XP efforts to CinnXP, for easier maintenance, so this problem should be solved.

**Comment by dominichayesferen** [comment]
@Elbullazul Odd, CinnXP was working on my main feren OS install, but when I tried it later in a Live CD, it didn't work 100% in 3.2, maybe I did the theme differently in feren OS by making it have the (non-built) Cinnamon, and the post-built GTK themes...

**Comment by dominichayesferen** [comment]
@Elbullazul Yeah, I think there's a problem with the way CinnXP builds themes for GTK 3.20 and Cinnamon, hang on, gonna test my theory...

**Comment by dominichayesferen** [comment]
@Elbullazul Working on it, fixed the popup menus, now for the CinnVIIStarkMenu (I'll add Cinn7's mods into a Pull Request here, as in the menu fixes, not the colour changes)

**Comment by dominichayesferen** [comment]
![screenshot from 2017-01-19 17-10-01](https://cloud.githubusercontent.com/assets/11057934/22116980/2505ea14-de6a-11e6-878a-55d17ae875ab.png)

**Comment by dominichayesferen** [comment]
@Elbullazul I fixed the menus, also, thanks for the fix to CinnVIIStarkMenu too

**Comment by dominichayesferen** [comment]
@Elbullazul You may need to look at my PR for Part 1

**Comment by Elbullazul** [comment]
@feren so, does it work now?

**Comment by cinnamoner** [comment]
Come to blank Christian.

**Comment by dominichayesferen** [comment]
@Elbullazul Yeah, apart from the IcingTaskManager which would probably be really hard to fix without his help

**Comment by Elbullazul** [comment]
@feren so XP themes are back again, finished the 'build script'

https://github.com/Elbullazul/WinXP-themes
