### ISSUE TITLE
Se7en theme on linux mint 18.1

### ISSUE THREAD

**Issue by f4bpp** [Elbullazul/Redmond-Themes#23]
Hi ! 

The se7en theme is really perfect on Linux Mint 18 but since last Cinnamon Update in Mint 18.1, there is a color problem and we get Grey instead of Blue. Minor improvements have to be done to fix that.

Thanks for the amazing work !

![capture du 2017-02-13 00-37-16](https://cloud.githubusercontent.com/assets/16517945/22892065/9089610c-f211-11e6-9e51-4bfc61f90f4f.png)

**Comment by dominichayesferen** [comment]
@magellan-13016 The gray means the theme doesn't work on the panel itself which means there may be a possible regression @Elbullazul with this version, as a previous version works fine here...

BTW: The menu is grey because this theme is only designed on 3.2 for these menus:
- Stock Cinnamon Menu
- CinnVIIStarkMenu (Looks closer to that menu you have there)
Other menus will be broken in these themes, though, given it's gray rather than looking like a menu, there's either a regression, or you may need to re-download the theme itself...

**Comment by Elbullazul** [comment]
@magellan-13016 open a terminal and type `cinnamon --replace`. Please post the output of the command (to restore the normal cinnamon session, run the same command but in the run-dialog (alt+f2)

**Comment by dominichayesferen** [comment]
@magellan-13016 Quicker way to restart Cinnamon via the run-dialog after running it in Terminal: `r` << Also works with GNOME 3+

**Comment by f4bpp** [comment]
As asked, here is my report :

**master@Asus-K55A ~/Bureau $ cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
parsing error: 4:1:could not recognize next production**

**(cinnamon:2206): St-WARNING : Error parsing stylesheet '/home/master/.themes/Mint-X-Aero (copie)/cinnamon/cinnamon.css'; errcode:15
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue Feb 14 2017 17:35:30 GMT+0100 (CET)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x6d not in stack
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55c9736107c0  Text: Master
Cjs-Message: JS LOG: Removing an access point that was never added**

_Nothing else happened after 10 minutes so I just copied thie lines and shutdown the computer._

**Comment by Elbullazul** [comment]
I see you renamed the theme folder. Does the same thing appears when applying the normal Se7en theme?

**Comment by dominichayesferen** [comment]
@Elbullazul That error says there's either something wrong with cinnamon.css in that theme, or there's a syntax error inside of the .css of that theme...

@magellan-13016 Any chance of uploading that in a zip here?

**Comment by f4bpp** [comment]
se7en theme has only a cinnamon folder. I just put it into my theme folder beside gtk-2.0, gtk-3.0 and metacity-1 folders. Here it is (with cinnamon.css updated from github) :

[Mint-X-Aero.zip](https://github.com/B00merang-Project/Redmond-Themes/files/775336/Mint-X-Aero.zip)

**Comment by f4bpp** [comment]
Please someone help me to fix the theme in the post above for Linux Mint 18.1. I really need it to keep my work since part of it is to recycle old PC with Linux OS for people used to Windows OS.

**Comment by Elbullazul** [comment]
I don't know what's the bug, really, at first sight.

maybe this weekend I can find the bug

**Comment by f4bpp** [comment]
Many thanks to try. Sincerely, I hope you'll find. You're my last chance.

**Comment by cinnamoner** [comment]
@Elbullazul Help him keep his job  :)

**Comment by Elbullazul** [comment]
I think I fixed it, it seems there was a `'` missing somewhere...

**Comment by cinnamoner** [comment]
@magellan-13016 You get to keep your job again. Hey, I recall you. 😉👍

**Comment by f4bpp** [comment]
Wonderful ! I knew you would find a solution for me. And this is not a joke, I really recycled old PC to Linux and thanks to themes like this people didn't notice anything for web browsing and Office works. And that's because the themes I used was perfect that my employer gave me this tasks. At his moment I work for another enterprise but in April, I should be employed again by my last employer for a teaching mission and PC recycling. My request is very serious. Thanks for the work.

**Comment by cinnamoner** [comment]
@magellan-13016 I'm glad Elbullazul could help you out. His an awesome guy.

**Comment by f4bpp** [comment]
Since I discovered his theme in Mint 18 I think he's an awesome guy too. ;-)

**Comment by f4bpp** [comment]
I've tried the last cinnamon.css and the problem still remain. Here is the cinnamon --replace post :

**master@Asus-K55A ~/Bureau $ cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
parsing error: 6:1:could not recognize next production**

**(cinnamon:2545): St-WARNING : Error parsing stylesheet '/home/master/.themes/Mint-X-Aero (copie)/cinnamon/cinnamon.css'; errcode:15
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Sat Feb 18 2017 10:05:24 GMT+0100 (CET)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x6d not in stack
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x5635f91387a0  Text: Master
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added**

**Comment by Elbullazul** [comment]
please try the vista theme in the same repo and see if it has the same issues. I'll re-base Se7en on this if it works. sorry for giving away false hopes @magellan-13016

**Comment by cinnamoner** [comment]
@magellan-13016 I'm anxiously waiting for your feedback. The Vista theme is equally beautiful.

**Comment by Elbullazul** [comment]
@magellan-13016 please try instead the latest Windows Se7en theme from master branch. I removed some broken links that may cause the bug. If the bug still persists, use the following file:
[Windows Se7en R4.1 (extended support).zip](https://github.com/B00merang-Project/Redmond-Themes/files/785949/Windows.Se7en.R4.1.extended.support.zip)

it's the last 'workable' version you used, adapted for 3.2

**Comment by cinnamoner** [comment]
Ha?

**Comment by cinnamoner** [comment]
Must be the weather or something. It's February.

**Comment by f4bpp** [comment]
Hi Elbullazul ! Many many and may thanks for your work ! Yes it works !

My tests : Vista Theme is working for the panel but not for the menu and the position of the vista button on the panel does not match with the one of the menu I use.

The se7en theme for the master branch works for the panel but not for the menu too (still grey color).

BUT... the Windows Se7en R4.1 (extended support) is working very well !

Thanks a lot ! Now all is running well except I find something wrong next days but I don't think I will.

I could not answer before since I was not at home for family reasons.

Once again, many thanks to you cause now I can call my boss and tell him I can recycle some old PC with last Linux Mint version and tune them like Windows 7. This time you didn't not only made a work for design reasons but for saving someone's work... You can be proud of it.

David.

**Comment by cinnamoner** [comment]
@magellan-13016 Night shift here. Elbullazul's probably sleeping. I'm glad your problem has been solved. Cya. 👍

**Comment by Elbullazul** [comment]
@magellan-13016 very glad it works, it's great to help someone keep their job! :D 

see you next time Mint upgrades cinnamon xD

**Comment by f4bpp** [comment]
You should add the extend version on your Boomerang site for people upgrading to last Mint 18.1. Many thanks for your help.

**Comment by cinnamoner** [comment]
@Elbullazul Indeed, you should

**Comment by Elbullazul** [comment]
on my 18.1 there's no bug, so...

**Comment by f4bpp** [comment]
How is it possible ? Mine is an update from 18 and not a fresh install. Could it be the origin of my problem ?

**Comment by Elbullazul** [comment]
@magellan-13016 maybe it's because my 18.1 is a vm and not updated
