### ISSUE TITLE
Compatibility with Transparent Panels (Vista Themes)

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#24]
What the title says since Vista made the taskbar an opaque black when a window is maximized.

**Comment by ghost** [comment]
@feren Screenshot?

**Comment by dominichayesferen** [comment]
@cinnamoner The only visible difference is an opaque panel when there's a maximised window...

**Comment by ghost** [comment]
@feren Obviously. But panel means nothing to me. I think you wanted to say titlebar.

**Comment by cinnamoner** [comment]
Everything boils down to whether it looks like Vista or it doesn't. I'm getting dizzy.

**Comment by ghost** [comment]
@feren Please check this out https://en.wikipedia.org/wiki/Window_decoration#Title_bar

In much beloved Vista, the title bar is transparent-frosty when not maximized and opaque when maximized. Actually kinda opaque pitch black.

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Window_manager cool :D

**Comment by dominichayesferen** [comment]
Since this is fixed and was in slight danger of going off-topic...

**Comment by cinnamoner** [comment]
It's was in slight danger of going nowhere rather. Mint-like habits. Let's close it man. Let's close it. By all means. Closing threads is the very purpose of our existence. I've noticed you mimicking others. Be yourself.
