### ISSUE TITLE
Updated Basic with working Show Desktop icon

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#27]
I just realised that the version of Basic I put in the Pull Request didn't have the Show Desktop button thing on it, so here's the version with it (and a feren OS orb):

**Comment by dominichayesferen** [comment]
[Windows Se7en Basic.tar.gz](https://github.com/B00merang-Project/Redmond-Themes/files/804794/Windows.Se7en.Basic.tar.gz)

**Comment by dominichayesferen** [comment]
@Elbullazul There you go. ^^

**Comment by cinnamoner** [comment]
Cool bro.
