### ISSUE TITLE
Padding in menu instead of menuitem!

### ISSUE THREAD

**Issue by ghost** [Elbullazul/Redmond-Themes#3]
Hi,

bluedxca93 here. Can you please move padding value from .menu and GTKComboboxmenu to .menu .menuitem thx. This bug cause drawing issues on 16.04 once drawing a menu. 
Implementing the padding only in .menu.menuitem and other child classes fixes the weird replicating of right and bottom border. 

looks like 
______I     I
______I__I

should be simply:
      I
___I

instead of:
.menu {
padding: x;
}

write:
.menu .menuitem {
padding: x
}

possibly this works too for something:
.menuitem:nth-child(last)
bla bla bla.

Don know if youre interested but: 

gsettings set org.cinnamon.desktop.interface icon-theme 'iconthemename'
gsettings set org.cinnamon.desktop.interface gtk-theme 'themename'
gsettings set org.cinnamon.desktop.wm.preferences theme 'themename'
gsettings set org.cinnamon.theme name 'themename'

for gnome/unity replace cinnamon with gnome. Set in iconthemename with desired icontheme and (gtk) themename.

Nortamlly this message would had been send as an pm on gnome-look, but since this site behave like a living zombie its written down here.

kind and best regards 
bluedxca93

**Comment by cinnamoner** [comment]
@bluedxca93 
Nice to hear from you. You know I always appreciate your input.

**Comment by cinnamoner** [comment]
Here's what I would like:
A StarkMenu that combines all the good elements from NicoKrause's and Bluedxca93's.
I understand that transitioning to 16.04 and Cinnamon 3.x.x is hard. Not to mention the gtk stuff.
Kind regards!

**Comment by cinnamoner** [comment]
@Elbullazul 
I tremendously appreciate the effort Bluedxca93 and NicoKrause have put into Stark. But I also think your repo should contain your very own StakMenu to fit your themes like a glove.

**Comment by ghost** [comment]
@cinnamoner no my stark menu version works on 3.0.0 too. It might break on 3.2 .

@elbullazul
This is gtk3 related. The menu and the toolbar design are the two most undocumented changes in gtk3. wrote here the most correctly workaround for menu. Note: You can simulate .menu padding by using an border image and  padding on menuitem. This way it ll be rendered correctly on  3.8 and 3.18.

**Comment by cinnamoner** [comment]
> no my stark menu version works on 3.0.0 too. It might break on 3.2 .

@bluedxca93 
I know that. It's my very point. 
Why don't you bring your artwork over to Git?  I recall you advising Elbullazul exactly that. And was a good advise. You're one of the few people I value greatly.

**Comment by Elbullazul** [comment]
Ok,  if I get this well,  instead of setting the padding for the menu I should set it on menu items to avoid some glitch.  Right?

**Comment by ghost** [comment]
@elbullazul yes and you need either box-shadow inset or a border image.
normally menuitem:hover schould load the value from menuitem.

@cinnamoner if i knew how i would upload most of it compressed without password from commandline to git.

**Comment by Elbullazul** [comment]
@bluedxca93 you know you can upload everything at once from the browser too?

you just have to create a release and upload all zips

**Comment by ghost** [comment]
@elbalazull
first revision of sed script done, can someone send me 3.18 and 3.20
adwaita theme generated css files?
do upload it today anyway on github but this would help a lot.
don't know how it performs but gets a lot right already.

**Comment by Elbullazul** [comment]
@bluedxca93 https://git.gnome.org/browse/gtk+/plain/gtk/theme/Adwaita/gtk-contained.css is for gtk 3.20 adwaita theme source code (css, not scss)

for gtk 3.18, I don't know, I don't have the code right now

**Comment by Elbullazul** [comment]
@bluedxca93 would you mind attaching a screenshot  of the issue? I'm just curious...

**Comment by Elbullazul** [comment]
this has been dealt with September's 18th Batch Release
