### ISSUE TITLE
Win9x in Ubuntu 17.10 / Gnome 3.26.2

### ISSUE THREAD

**Issue by ways** [Elbullazul/Redmond-Themes#38]
Hi

I'm unable to get the normal task bar as seen in https://b00merang.weebly.com/uploads/1/6/8/1/16813022/449303749-orig-orig_orig.png

I've tried https://extensions.gnome.org/extension/1160/dash-to-panel/, but that enables background matching theme for the panel. See https://users.no/index.php/s/RYGkrqIUK56VSWm

Any tips?

**Comment by Elbullazul** [comment]
The desktop in the screenshots is cinnamon. You could try dash2dock it but it doesn't play nice with gnome.

Maybe try xfce4 panel?
