### ISSUE TITLE
Checkboxes do now show on Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by falsechicken** [Elbullazul/Redmond-Themes#40]
Hello! I love the Windows9x theme but I am having a problem. The checkboxes do now show up. This happens to a few of the themes in the repo. When I right click the desktop there is an empty space where the checkboxes should be (Next to Keep Aligned or Organize Desktop By Name). The Windows 95 theme works fine so I am using this for now. I am using the latest version from git as of when this issue was posted.

Here is the issue in action: 

![issue](https://user-images.githubusercontent.com/401328/39550560-aedaf28a-4e2f-11e8-8a11-16a0f61674ad.gif)

**Comment by Elbullazul** [comment]
Hello,

Glad you like our themes!

The windows 3.x and 9x themes have almost reached their respective EOLs, and will not be supported from then on.

The Windows 3.11 and 95 themes will replace them once they're ready for release

I didn't notice the Windows basic theme included a GTK theme. Will fix in the coming weeks

**Comment by falsechicken** [comment]
:+1: 
Ah ok. I like the 95 theme well enough so that's great that it's going to be supported. Thanks! Guess this is no longer necessary then xD.
