### ISSUE TITLE
Possible theme install script

### ISSUE THREAD

**Issue by ghost** [Elbullazul/Redmond-Themes#5]
@feren @Elbullazul 
[dark-theme-installer.txt](https://github.com/Elbullazul/Redmond-Themes/files/322820/dark-theme-installer.txt)
./script theme-archive-name

 only supports single archives at the mioment
maybe can be extended to load from github if git installed too.

**Comment by Elbullazul** [comment]
@bluedxca93 had some spare time and decided to do this.  It's incomplete and a little dirty (could rewrite some functions),  but it works. 

Update feature is unavailable at the moment 

https://github.com/Elbullazul/B00merang-Transformer

**Comment by ghost** [comment]
@feren its not much less secure or complete than your script atm.Yours is more focused on downloading.  the good thing is it recovers theme name correctly from theme archive name and supports nearly all formats while beeing small.
we can add a special checksum thing to it quickly.
extend it to http is also possible.
