### ISSUE TITLE
Glitch With StarkMenu (EMBEDDED)

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#8]
I tried the Embedded theme, and this oddity happens: (Look at window)
![screenshot from 2016-09-24 11-44-51](https://cloud.githubusercontent.com/assets/11057934/18808277/e21797c6-824c-11e6-961d-de20ec3d01c9.png)

Also, @Elbullazul , you may want to borrow some code from the plex port to make the menu work properly...

**Comment by Elbullazul** [comment]
I did get code from plex, but I guess your menu doesn't have text. try adding 'start' to the menu

does that only happen with weather?

**Comment by dominichayesferen** [comment]
@Elbullazul I was meaning the bit on the menu where it has the right-side items, also, the top and bottom bars look wrongly placed

**Comment by dominichayesferen** [comment]
Odd, it isn't happening anymore... :/, guess I'll rename the title to focus on the menu then

**Comment by dominichayesferen** [comment]
Also, when it was happening, a new window would actually make it maximise properly oddly enough

**Comment by dominichayesferen** [comment]
For the menu: Borrow the code in the StarkMenu section for the right-pane to get it working properly and then get code off of CinnXP and Plex for the top and bottom parts of the menu...

**Comment by Elbullazul** [comment]
got it working, but as this shows, you need text for stark to display properly

**Comment by dominichayesferen** [comment]
@Elbullazul Err, before I update, text didn't change ANYTHING! (Neither does User Text or Shutdown text)
![screenshot from 2016-09-25 15-35-30](https://cloud.githubusercontent.com/assets/11057934/18816289/c09d08e4-8335-11e6-874f-9825077d6ad7.png)

**Comment by dominichayesferen** [comment]
Can you release the latest update to GitHub so I can test it??

**Comment by Elbullazul** [comment]
shure, just a moment...

![screenshot_2016-09-25_09-58-15](https://cloud.githubusercontent.com/assets/15310985/18816519/ff9f3e20-8319-11e6-92c7-56b07ebdb997.png)
![screenshot_2016-09-25_09-58-25](https://cloud.githubusercontent.com/assets/15310985/18816520/00d563c8-831a-11e6-99d4-012bed062a3b.png)

**Comment by dominichayesferen** [comment]
Can you test it like so:
User label off
Shutdown buttons next-to-each other

Also, you may also want to fix the blue square shade change position in the middle of the menu

**Comment by Elbullazul** [comment]
![screenshot_2016-09-25_12-34-45](https://cloud.githubusercontent.com/assets/15310985/18816674/7408ee12-831c-11e6-9c34-2a1f3c3044ba.png)

**Comment by dominichayesferen** [comment]
@Elbullazul That's better! ;D

**Comment by dominichayesferen** [comment]
@Elbullazul Now headerbars in Zune??

**Comment by Elbullazul** [comment]
what? same problem?

**Comment by dominichayesferen** [comment]
@Elbullazul No, I was meaning have you given Zune the headerbar treatment yet?

**Comment by Elbullazul** [comment]
![screenshot_2016-09-25_12-14-42](https://cloud.githubusercontent.com/assets/15310985/18817915/33935390-833a-11e6-8dbf-deca50f12cae.png)

**Comment by dominichayesferen** [comment]
Sweet! :D
Also, you might want to re-add the toolbar butttons on hover and pressed for the Nemo window to make it more XP-esque and make it look better... :D

**Comment by dominichayesferen** [comment]
I've been suffering lots of hiding glitches with controls on Zune for some reason now... :/
(especially in Pantheon Photos and GTK Dialogs)

**Comment by Elbullazul** [comment]
maybe GTK inconsistencies? weren't you on cinnamon unstable?

**Comment by dominichayesferen** [comment]
@Elbullazul Yeah, but still, didn't happen with feren GTK or any others though... :/

**Comment by Elbullazul** [comment]
Royale Dark on the works...
![screenshot_2016-10-06_17-58-35](https://cloud.githubusercontent.com/assets/15310985/19173705/4768f508-8bf7-11e6-9ca4-ba2deeaf2e3a.png)
