### ISSUE TITLE
[3.1] Suggested Icon Pack missing Cinnamon Settings icons

### ISSUE THREAD

**Issue by dominichayesferen** [Elbullazul/Redmond-Themes#9]
On your screenshot of 3.1, there's some Cinnamon Settings icons whilst on the icon set you linked to in the suggestion, it's missing those icons and you just get something like this:
![screenshot from 2016-09-25 15-46-21](https://cloud.githubusercontent.com/assets/11057934/18816347/61eafac0-8337-11e6-8ae3-13932660e95c.png)

**Comment by Elbullazul** [comment]
uploading in short, just have to find it in the tons of backups I have...

**Comment by dominichayesferen** [comment]
Any Update?

**Comment by Elbullazul** [comment]
found, uploading in short, but it's almost like ylmfos's decadency...

EDIT: doesn't look so bad...

**Comment by Elbullazul** [comment]
[Classic95.tar.gz](https://github.com/Elbullazul/Redmond-Themes/files/493778/Classic95.tar.gz)
